#import <ElvenUnifiedObservabilityReactNativeSpec/ElvenUnifiedObservabilityReactNativeSpec.h>

@interface ElvenUnifiedObservabilityReactNative : NSObject <NativeElvenUnifiedObservabilityReactNativeSpec>

@end
